{% set version = "0.2.1" %}

package:
  name: pymagewell
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/p/pymagewell/pymagewell-{{ version }}.tar.gz
    sha256: 70cdf755fe6001a871a97b987f1e9b3d67ba97f5f2a23675f6e0fa717a457a37
  - url: https://github.com/KCL-BMEIS/pymagewell/archive/refs/tags/v{{ version }}.tar.gz
    sha256: ec32e4efff7f52b3be83a8fe6d5b969c2212365d0b5abe8a2bdd016083c0e19e
    folder: test-data

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39 or linux or python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - numpy >=1.23.4
    - pywin32 >=304  # [win]
    - python
    - libopencv >=4.6.0
    - opencv >=4.6.0
    - py-opencv >=4.6.0
test:
  imports:
    - mwcapture
    - pymagewell
  requires:
    - pip
    - pytest ==7.4.3
  source_files:
    - test-data/src/tests
  commands:
    - pip check
    - pytest  # [win]

about:
  home: https://github.com/KCL-BMEIS/pymagewell
  summary: Python library for interfacing with Magewell ProCapture frame grabbers
  description: |
    pymagewell is a Python library for interfacing with Magewell ProCapture frame grabbers. It is based on (and includes) Magewell's Windows SDK and is therefore Windows only. However, it provides a mock class for testing and development that does not depend on the SDK's Windows .dll files, so pymagwell can also be installed on macOS and Linux.
  doc_url: https://kcl-bmeis.github.io/pymagewell/
  dev_url: https://github.com/KCL-BMEIS/pymagewell
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - crnbaker
